/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QAPI visitor functions
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#include "qapi-visit.h"

void visit_type_NameInfo(Visitor *m, NameInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "NameInfo", name, sizeof(NameInfo), errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_name : NULL, "name", errp);
    if ((*obj)->has_name) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->name : NULL, "name", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_NameInfoList(Visitor *m, NameInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        NameInfoList *native_i = (NameInfoList *)i;
        visit_type_NameInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_VersionInfo(Visitor *m, VersionInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "VersionInfo", name, sizeof(VersionInfo), errp);
    visit_start_struct(m, NULL, "", "qemu", 0, errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->qemu.major : NULL, "major", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->qemu.minor : NULL, "minor", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->qemu.micro : NULL, "micro", errp);
    visit_end_struct(m, errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->package : NULL, "package", errp);
    visit_end_struct(m, errp);
}

void visit_type_VersionInfoList(Visitor *m, VersionInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        VersionInfoList *native_i = (VersionInfoList *)i;
        visit_type_VersionInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_KvmInfo(Visitor *m, KvmInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "KvmInfo", name, sizeof(KvmInfo), errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->enabled : NULL, "enabled", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->present : NULL, "present", errp);
    visit_end_struct(m, errp);
}

void visit_type_KvmInfoList(Visitor *m, KvmInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        KvmInfoList *native_i = (KvmInfoList *)i;
        visit_type_KvmInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_RunState(Visitor *m, RunState * obj, const char *name, Error **errp)
{
    visit_type_enum(m, (int *)obj, RunState_lookup, "RunState", name, errp);
}

void visit_type_StatusInfo(Visitor *m, StatusInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "StatusInfo", name, sizeof(StatusInfo), errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->running : NULL, "running", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->singlestep : NULL, "singlestep", errp);
    visit_type_RunState(m, (obj && *obj) ? &(*obj)->status : NULL, "status", errp);
    visit_end_struct(m, errp);
}

void visit_type_StatusInfoList(Visitor *m, StatusInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        StatusInfoList *native_i = (StatusInfoList *)i;
        visit_type_StatusInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_UuidInfo(Visitor *m, UuidInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "UuidInfo", name, sizeof(UuidInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->UUID : NULL, "UUID", errp);
    visit_end_struct(m, errp);
}

void visit_type_UuidInfoList(Visitor *m, UuidInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        UuidInfoList *native_i = (UuidInfoList *)i;
        visit_type_UuidInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_ChardevInfo(Visitor *m, ChardevInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "ChardevInfo", name, sizeof(ChardevInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->label : NULL, "label", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->filename : NULL, "filename", errp);
    visit_end_struct(m, errp);
}

void visit_type_ChardevInfoList(Visitor *m, ChardevInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        ChardevInfoList *native_i = (ChardevInfoList *)i;
        visit_type_ChardevInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_CommandInfo(Visitor *m, CommandInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "CommandInfo", name, sizeof(CommandInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->name : NULL, "name", errp);
    visit_end_struct(m, errp);
}

void visit_type_CommandInfoList(Visitor *m, CommandInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        CommandInfoList *native_i = (CommandInfoList *)i;
        visit_type_CommandInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_MigrationStats(Visitor *m, MigrationStats ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "MigrationStats", name, sizeof(MigrationStats), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->transferred : NULL, "transferred", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->remaining : NULL, "remaining", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->total : NULL, "total", errp);
    visit_end_struct(m, errp);
}

void visit_type_MigrationStatsList(Visitor *m, MigrationStatsList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        MigrationStatsList *native_i = (MigrationStatsList *)i;
        visit_type_MigrationStats(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_MigrationInfo(Visitor *m, MigrationInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "MigrationInfo", name, sizeof(MigrationInfo), errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_status : NULL, "status", errp);
    if ((*obj)->has_status) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->status : NULL, "status", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_ram : NULL, "ram", errp);
    if ((*obj)->has_ram) {
        visit_type_MigrationStats(m, (obj && *obj) ? &(*obj)->ram : NULL, "ram", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_disk : NULL, "disk", errp);
    if ((*obj)->has_disk) {
        visit_type_MigrationStats(m, (obj && *obj) ? &(*obj)->disk : NULL, "disk", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_MigrationInfoList(Visitor *m, MigrationInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        MigrationInfoList *native_i = (MigrationInfoList *)i;
        visit_type_MigrationInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_MouseInfo(Visitor *m, MouseInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "MouseInfo", name, sizeof(MouseInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->name : NULL, "name", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->index : NULL, "index", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->current : NULL, "current", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->absolute : NULL, "absolute", errp);
    visit_end_struct(m, errp);
}

void visit_type_MouseInfoList(Visitor *m, MouseInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        MouseInfoList *native_i = (MouseInfoList *)i;
        visit_type_MouseInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_CpuInfo(Visitor *m, CpuInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "CpuInfo", name, sizeof(CpuInfo), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->CPU : NULL, "CPU", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->current : NULL, "current", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->halted : NULL, "halted", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_pc : NULL, "pc", errp);
    if ((*obj)->has_pc) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->pc : NULL, "pc", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_nip : NULL, "nip", errp);
    if ((*obj)->has_nip) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->nip : NULL, "nip", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_npc : NULL, "npc", errp);
    if ((*obj)->has_npc) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->npc : NULL, "npc", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_PC : NULL, "PC", errp);
    if ((*obj)->has_PC) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->PC : NULL, "PC", errp);
    }
    visit_end_optional(m, errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->thread_id : NULL, "thread_id", errp);
    visit_end_struct(m, errp);
}

void visit_type_CpuInfoList(Visitor *m, CpuInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        CpuInfoList *native_i = (CpuInfoList *)i;
        visit_type_CpuInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_BlockDeviceInfo(Visitor *m, BlockDeviceInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "BlockDeviceInfo", name, sizeof(BlockDeviceInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->file : NULL, "file", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->ro : NULL, "ro", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->drv : NULL, "drv", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_backing_file : NULL, "backing_file", errp);
    if ((*obj)->has_backing_file) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->backing_file : NULL, "backing_file", errp);
    }
    visit_end_optional(m, errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->encrypted : NULL, "encrypted", errp);
    visit_end_struct(m, errp);
}

void visit_type_BlockDeviceInfoList(Visitor *m, BlockDeviceInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        BlockDeviceInfoList *native_i = (BlockDeviceInfoList *)i;
        visit_type_BlockDeviceInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_BlockDeviceIoStatus(Visitor *m, BlockDeviceIoStatus * obj, const char *name, Error **errp)
{
    visit_type_enum(m, (int *)obj, BlockDeviceIoStatus_lookup, "BlockDeviceIoStatus", name, errp);
}

void visit_type_BlockInfo(Visitor *m, BlockInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "BlockInfo", name, sizeof(BlockInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->device : NULL, "device", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->type : NULL, "type", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->removable : NULL, "removable", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->locked : NULL, "locked", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_inserted : NULL, "inserted", errp);
    if ((*obj)->has_inserted) {
        visit_type_BlockDeviceInfo(m, (obj && *obj) ? &(*obj)->inserted : NULL, "inserted", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_tray_open : NULL, "tray_open", errp);
    if ((*obj)->has_tray_open) {
        visit_type_bool(m, (obj && *obj) ? &(*obj)->tray_open : NULL, "tray_open", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_io_status : NULL, "io-status", errp);
    if ((*obj)->has_io_status) {
        visit_type_BlockDeviceIoStatus(m, (obj && *obj) ? &(*obj)->io_status : NULL, "io-status", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_BlockInfoList(Visitor *m, BlockInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        BlockInfoList *native_i = (BlockInfoList *)i;
        visit_type_BlockInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_BlockDeviceStats(Visitor *m, BlockDeviceStats ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "BlockDeviceStats", name, sizeof(BlockDeviceStats), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->rd_bytes : NULL, "rd_bytes", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->wr_bytes : NULL, "wr_bytes", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->rd_operations : NULL, "rd_operations", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->wr_operations : NULL, "wr_operations", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->flush_operations : NULL, "flush_operations", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->flush_total_time_ns : NULL, "flush_total_time_ns", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->wr_total_time_ns : NULL, "wr_total_time_ns", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->rd_total_time_ns : NULL, "rd_total_time_ns", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->wr_highest_offset : NULL, "wr_highest_offset", errp);
    visit_end_struct(m, errp);
}

void visit_type_BlockDeviceStatsList(Visitor *m, BlockDeviceStatsList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        BlockDeviceStatsList *native_i = (BlockDeviceStatsList *)i;
        visit_type_BlockDeviceStats(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_BlockStats(Visitor *m, BlockStats ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "BlockStats", name, sizeof(BlockStats), errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_device : NULL, "device", errp);
    if ((*obj)->has_device) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->device : NULL, "device", errp);
    }
    visit_end_optional(m, errp);
    visit_type_BlockDeviceStats(m, (obj && *obj) ? &(*obj)->stats : NULL, "stats", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_parent : NULL, "parent", errp);
    if ((*obj)->has_parent) {
        visit_type_BlockStats(m, (obj && *obj) ? &(*obj)->parent : NULL, "parent", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_BlockStatsList(Visitor *m, BlockStatsList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        BlockStatsList *native_i = (BlockStatsList *)i;
        visit_type_BlockStats(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_VncClientInfo(Visitor *m, VncClientInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "VncClientInfo", name, sizeof(VncClientInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->host : NULL, "host", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->family : NULL, "family", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->service : NULL, "service", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_x509_dname : NULL, "x509_dname", errp);
    if ((*obj)->has_x509_dname) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->x509_dname : NULL, "x509_dname", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_sasl_username : NULL, "sasl_username", errp);
    if ((*obj)->has_sasl_username) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->sasl_username : NULL, "sasl_username", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_VncClientInfoList(Visitor *m, VncClientInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        VncClientInfoList *native_i = (VncClientInfoList *)i;
        visit_type_VncClientInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_VncInfo(Visitor *m, VncInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "VncInfo", name, sizeof(VncInfo), errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->enabled : NULL, "enabled", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_host : NULL, "host", errp);
    if ((*obj)->has_host) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->host : NULL, "host", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_family : NULL, "family", errp);
    if ((*obj)->has_family) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->family : NULL, "family", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_service : NULL, "service", errp);
    if ((*obj)->has_service) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->service : NULL, "service", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_auth : NULL, "auth", errp);
    if ((*obj)->has_auth) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->auth : NULL, "auth", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_clients : NULL, "clients", errp);
    if ((*obj)->has_clients) {
        visit_type_VncClientInfoList(m, (obj && *obj) ? &(*obj)->clients : NULL, "clients", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_VncInfoList(Visitor *m, VncInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        VncInfoList *native_i = (VncInfoList *)i;
        visit_type_VncInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_SpiceChannel(Visitor *m, SpiceChannel ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "SpiceChannel", name, sizeof(SpiceChannel), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->host : NULL, "host", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->family : NULL, "family", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->port : NULL, "port", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->connection_id : NULL, "connection-id", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->channel_type : NULL, "channel-type", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->channel_id : NULL, "channel-id", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->tls : NULL, "tls", errp);
    visit_end_struct(m, errp);
}

void visit_type_SpiceChannelList(Visitor *m, SpiceChannelList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        SpiceChannelList *native_i = (SpiceChannelList *)i;
        visit_type_SpiceChannel(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_SpiceInfo(Visitor *m, SpiceInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "SpiceInfo", name, sizeof(SpiceInfo), errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->enabled : NULL, "enabled", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_host : NULL, "host", errp);
    if ((*obj)->has_host) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->host : NULL, "host", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_port : NULL, "port", errp);
    if ((*obj)->has_port) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->port : NULL, "port", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_tls_port : NULL, "tls-port", errp);
    if ((*obj)->has_tls_port) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->tls_port : NULL, "tls-port", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_auth : NULL, "auth", errp);
    if ((*obj)->has_auth) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->auth : NULL, "auth", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_compiled_version : NULL, "compiled-version", errp);
    if ((*obj)->has_compiled_version) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->compiled_version : NULL, "compiled-version", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_channels : NULL, "channels", errp);
    if ((*obj)->has_channels) {
        visit_type_SpiceChannelList(m, (obj && *obj) ? &(*obj)->channels : NULL, "channels", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_SpiceInfoList(Visitor *m, SpiceInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        SpiceInfoList *native_i = (SpiceInfoList *)i;
        visit_type_SpiceInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_BalloonInfo(Visitor *m, BalloonInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "BalloonInfo", name, sizeof(BalloonInfo), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->actual : NULL, "actual", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_mem_swapped_in : NULL, "mem_swapped_in", errp);
    if ((*obj)->has_mem_swapped_in) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->mem_swapped_in : NULL, "mem_swapped_in", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_mem_swapped_out : NULL, "mem_swapped_out", errp);
    if ((*obj)->has_mem_swapped_out) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->mem_swapped_out : NULL, "mem_swapped_out", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_major_page_faults : NULL, "major_page_faults", errp);
    if ((*obj)->has_major_page_faults) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->major_page_faults : NULL, "major_page_faults", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_minor_page_faults : NULL, "minor_page_faults", errp);
    if ((*obj)->has_minor_page_faults) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->minor_page_faults : NULL, "minor_page_faults", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_free_mem : NULL, "free_mem", errp);
    if ((*obj)->has_free_mem) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->free_mem : NULL, "free_mem", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_total_mem : NULL, "total_mem", errp);
    if ((*obj)->has_total_mem) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->total_mem : NULL, "total_mem", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_BalloonInfoList(Visitor *m, BalloonInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        BalloonInfoList *native_i = (BalloonInfoList *)i;
        visit_type_BalloonInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_PciMemoryRange(Visitor *m, PciMemoryRange ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "PciMemoryRange", name, sizeof(PciMemoryRange), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->base : NULL, "base", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->limit : NULL, "limit", errp);
    visit_end_struct(m, errp);
}

void visit_type_PciMemoryRangeList(Visitor *m, PciMemoryRangeList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        PciMemoryRangeList *native_i = (PciMemoryRangeList *)i;
        visit_type_PciMemoryRange(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_PciMemoryRegion(Visitor *m, PciMemoryRegion ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "PciMemoryRegion", name, sizeof(PciMemoryRegion), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->bar : NULL, "bar", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->type : NULL, "type", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->address : NULL, "address", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->size : NULL, "size", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_prefetch : NULL, "prefetch", errp);
    if ((*obj)->has_prefetch) {
        visit_type_bool(m, (obj && *obj) ? &(*obj)->prefetch : NULL, "prefetch", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_mem_type_64 : NULL, "mem_type_64", errp);
    if ((*obj)->has_mem_type_64) {
        visit_type_bool(m, (obj && *obj) ? &(*obj)->mem_type_64 : NULL, "mem_type_64", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_PciMemoryRegionList(Visitor *m, PciMemoryRegionList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        PciMemoryRegionList *native_i = (PciMemoryRegionList *)i;
        visit_type_PciMemoryRegion(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_PciBridgeInfo(Visitor *m, PciBridgeInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "PciBridgeInfo", name, sizeof(PciBridgeInfo), errp);
    visit_start_struct(m, NULL, "", "bus", 0, errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->bus.number : NULL, "number", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->bus.secondary : NULL, "secondary", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->bus.subordinate : NULL, "subordinate", errp);
    visit_type_PciMemoryRange(m, (obj && *obj) ? &(*obj)->bus.io_range : NULL, "io_range", errp);
    visit_type_PciMemoryRange(m, (obj && *obj) ? &(*obj)->bus.memory_range : NULL, "memory_range", errp);
    visit_type_PciMemoryRange(m, (obj && *obj) ? &(*obj)->bus.prefetchable_range : NULL, "prefetchable_range", errp);
    visit_end_struct(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_devices : NULL, "devices", errp);
    if ((*obj)->has_devices) {
        visit_type_PciDeviceInfoList(m, (obj && *obj) ? &(*obj)->devices : NULL, "devices", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_PciBridgeInfoList(Visitor *m, PciBridgeInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        PciBridgeInfoList *native_i = (PciBridgeInfoList *)i;
        visit_type_PciBridgeInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_PciDeviceInfo(Visitor *m, PciDeviceInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "PciDeviceInfo", name, sizeof(PciDeviceInfo), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->bus : NULL, "bus", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->slot : NULL, "slot", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->function : NULL, "function", errp);
    visit_start_struct(m, NULL, "", "class_info", 0, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->class_info.has_desc : NULL, "desc", errp);
    if ((*obj)->class_info.has_desc) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->class_info.desc : NULL, "desc", errp);
    }
    visit_end_optional(m, errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->class_info.class : NULL, "class", errp);
    visit_end_struct(m, errp);
    visit_start_struct(m, NULL, "", "id", 0, errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->id.device : NULL, "device", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->id.vendor : NULL, "vendor", errp);
    visit_end_struct(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_irq : NULL, "irq", errp);
    if ((*obj)->has_irq) {
        visit_type_int(m, (obj && *obj) ? &(*obj)->irq : NULL, "irq", errp);
    }
    visit_end_optional(m, errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->qdev_id : NULL, "qdev_id", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_pci_bridge : NULL, "pci_bridge", errp);
    if ((*obj)->has_pci_bridge) {
        visit_type_PciBridgeInfo(m, (obj && *obj) ? &(*obj)->pci_bridge : NULL, "pci_bridge", errp);
    }
    visit_end_optional(m, errp);
    visit_type_PciMemoryRegionList(m, (obj && *obj) ? &(*obj)->regions : NULL, "regions", errp);
    visit_end_struct(m, errp);
}

void visit_type_PciDeviceInfoList(Visitor *m, PciDeviceInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        PciDeviceInfoList *native_i = (PciDeviceInfoList *)i;
        visit_type_PciDeviceInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_PciInfo(Visitor *m, PciInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "PciInfo", name, sizeof(PciInfo), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->bus : NULL, "bus", errp);
    visit_type_PciDeviceInfoList(m, (obj && *obj) ? &(*obj)->devices : NULL, "devices", errp);
    visit_end_struct(m, errp);
}

void visit_type_PciInfoList(Visitor *m, PciInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        PciInfoList *native_i = (PciInfoList *)i;
        visit_type_PciInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}
