/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QAPI visitor function
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#ifndef QGA_QAPI_VISIT_H
#define QGA_QAPI_VISIT_H

#include "qapi/qapi-visit-core.h"
#include "qga-qapi-types.h"

void visit_type_GuestAgentInfo(Visitor *m, GuestAgentInfo ** obj, const char *name, Error **errp);
void visit_type_GuestAgentInfoList(Visitor *m, GuestAgentInfoList ** obj, const char *name, Error **errp);

void visit_type_GuestFileRead(Visitor *m, GuestFileRead ** obj, const char *name, Error **errp);
void visit_type_GuestFileReadList(Visitor *m, GuestFileReadList ** obj, const char *name, Error **errp);

void visit_type_GuestFileWrite(Visitor *m, GuestFileWrite ** obj, const char *name, Error **errp);
void visit_type_GuestFileWriteList(Visitor *m, GuestFileWriteList ** obj, const char *name, Error **errp);

void visit_type_GuestFileSeek(Visitor *m, GuestFileSeek ** obj, const char *name, Error **errp);
void visit_type_GuestFileSeekList(Visitor *m, GuestFileSeekList ** obj, const char *name, Error **errp);

void visit_type_GuestFsfreezeStatus(Visitor *m, GuestFsfreezeStatus * obj, const char *name, Error **errp);

#endif
