/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QAPI visitor functions
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#include "qga-qapi-visit.h"

void visit_type_GuestAgentInfo(Visitor *m, GuestAgentInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "GuestAgentInfo", name, sizeof(GuestAgentInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->version : NULL, "version", errp);
    visit_end_struct(m, errp);
}

void visit_type_GuestAgentInfoList(Visitor *m, GuestAgentInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        GuestAgentInfoList *native_i = (GuestAgentInfoList *)i;
        visit_type_GuestAgentInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFileRead(Visitor *m, GuestFileRead ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "GuestFileRead", name, sizeof(GuestFileRead), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->count : NULL, "count", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->buf_b64 : NULL, "buf-b64", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->eof : NULL, "eof", errp);
    visit_end_struct(m, errp);
}

void visit_type_GuestFileReadList(Visitor *m, GuestFileReadList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        GuestFileReadList *native_i = (GuestFileReadList *)i;
        visit_type_GuestFileRead(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFileWrite(Visitor *m, GuestFileWrite ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "GuestFileWrite", name, sizeof(GuestFileWrite), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->count : NULL, "count", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->eof : NULL, "eof", errp);
    visit_end_struct(m, errp);
}

void visit_type_GuestFileWriteList(Visitor *m, GuestFileWriteList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        GuestFileWriteList *native_i = (GuestFileWriteList *)i;
        visit_type_GuestFileWrite(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFileSeek(Visitor *m, GuestFileSeek ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "GuestFileSeek", name, sizeof(GuestFileSeek), errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->position : NULL, "position", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->eof : NULL, "eof", errp);
    visit_end_struct(m, errp);
}

void visit_type_GuestFileSeekList(Visitor *m, GuestFileSeekList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        GuestFileSeekList *native_i = (GuestFileSeekList *)i;
        visit_type_GuestFileSeek(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFsfreezeStatus(Visitor *m, GuestFsfreezeStatus * obj, const char *name, Error **errp)
{
    visit_type_enum(m, (int *)obj, GuestFsfreezeStatus_lookup, "GuestFsfreezeStatus", name, errp);
}
